INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (1, 'SMARTPHONE', 1000000);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (2, 'NOTEBOOK', 1000000);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (3, 'TABLET', 1000000);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (4, 'KEYBOARD', 1000000);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (5, 'MOUSE', 1000000);