INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (1, 'SMARTPHONE', 4);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (2, 'NOTEBOOK', 2);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (3, 'TABLET', 5);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (4, 'KEYBOARD', 7);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (5, 'MOUSE', 9);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (6, 'HEADPHONE', 9);