version: '3.8'

services:
  toxiproxy:
    image: shopify/toxiproxy:latest
    container_name: toxiproxy-chaos
    ports:
      - "8474:8474"  # API port
      - "8090:8090"  # Proxy port for order service
    command: ["toxiproxy-server", "-host", "0.0.0.0", "-port", "8474"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8474/version"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - TOXIPROXY_HOST=0.0.0.0